all: graph.o main.o
	gcc graph.o main.c -o main -std=c99 -Wall -lm 

graph.o:
		gcc -c graph.c -o graph.o

run: 
	valgrind --leak-check=full ./main 

clean: 
	rm graph.o 
	rm main 
	rm main.o

tudo: 
	make -s clean 
	make -s 
	make -s run  
